# Generated by Django 5.0.2 on 2024-02-28 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Обращение рассмотрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время ответа')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bot_app.civilcomplaint', verbose_name='Обращение')),
            ],
        ),
    ]
