# Generated by Django 4.2.10 on 2024-02-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot_app', '0003_rename_subject_appeal_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обращения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Обращение рассмотрено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Гражданское обращение',
                'verbose_name_plural': 'Гражданские обращения',
            },
        ),
        migrations.CreateModel(
            name='EmployeeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время ответа')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bot_app.civilcomplaint', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Ответ сотрудника',
                'verbose_name_plural': 'Ответы сотрудников',
            },
        ),
        migrations.DeleteModel(
            name='Appeal',
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
    ]
